export let products = [
    { name: "Sweetheart Roast", cost: 15.59, category: "Coffee"},
    { name: "Classic Light Roast", cost: 25.99, category: "Coffee"},
    { name: "Classic Medium Roast", cost: 25.99, category: "Coffee"},
    { name: "Classic Dark Roast", cost: 25.99, category: "Coffee"},
    { name: "Single Shot of Espresso", cost: 4.00, category: "Coffee"},
    { name: "Americano", cost: 7.25, category: "Coffee"},
    { name: "Cortado", cost: 6.50, category: "Coffee"},
    { name: "Macchiato", cost: 6.99, category: "Coffee"},
    { name: "Capuccino", cost: 7.25, category: "Coffee"},
    { name: "Black Tea", cost: 3.00, category: "Tea"},
    { name: "Chamomile Tea", cost: 3.25, category: "Tea"},
    { name: "Green Tea", cost: 4.00, category: "Tea"},
    { name: "Bubble Tea", cost: 7.50, category: "Tea"},
    { name: "Jasmine Tea", cost: 4.25, category: "Tea"},
    { name: "Hibiscus Tea", cost: 3.00, category: "Tea"},
    { name: "Kombucha", cost: 5.25, category: "Tea"},
    { name: "Lemongrass Tea", cost: 3.25, category: "Tea"},
    { name: "Lavender Tea", cost: 3.00, category: "Tea"},
    { name: "Kozy Kitty Mug", cost: 11.99, category: "Accessories"},
    { name: "Catffeinated Coffee Mug", cost: 13.99, category: "Accessories"},
    { name: "Ceramic Matching Mug Set", cost: 24.99, category: "Accessories"},
    { name: "French Press", cost: 15.50, category: "Accessories"},
    { name: "Cutie Cat Teabag Holder", cost: 4.00, category: "Accessories"},
    { name: "Meow Meow Teapot", cost: 22.99, category: "Accessories"},
    { name: "Coffee Grounds Scale", cost: 37.00, category: "Accessories"},
    { name: "Coffee With Cattitude Mug", cost: 13.99, category: "Accessories"},
    { name: "Adorable Kitty Mug With Lid & Spoon", cost: 15.99, category: "Accessories"}    
];